const eventsList = [
  // ── CONCERTS ──────────────────────────────────────────────────
  {
    id: '1',
    title: 'Coldplay: Music of the Spheres World Tour',
    type: 'Concert',
    artist: 'Coldplay',
    genre: 'pop/rock',
    date: '2026-05-21',
    time: '8:00 PM',
    location: 'Delhi',
    price: '₹4,500',
    description: 'Coldplay brings their record-breaking Music of the Spheres World Tour to India with a spectacular light show and pyrotechnics.',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'pop', 'rock', 'international', 'concert']
  },
  {
    id: '2',
    title: 'AR Rahman: Infinite Love Tour',
    type: 'Concert',
    artist: 'AR Rahman',
    genre: 'indian classical/fusion',
    date: '2026-06-15',
    time: '7:30 PM',
    location: 'Mumbai',
    price: '₹2,000',
    description: 'An evening of musical magic with the Oscar-winning Mozart of Madras featuring his greatest hits from Bollywood and beyond.',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'indian', 'bollywood', 'concert', 'fusion']
  },
  {
    id: '3',
    title: 'Arijit Singh Live in Concert',
    type: 'Concert',
    artist: 'Arijit Singh',
    genre: 'bollywood',
    date: '2026-08-05',
    time: '7:00 PM',
    location: 'Mumbai',
    price: '₹2,500',
    description: "Experience the magic of Arijit Singh's soulful voice performing his greatest Bollywood hits live.",
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'bollywood', 'vocal', 'concert']
  },
  {
    id: '4',
    title: 'Diljit Dosanjh: Dil-Luminati Tour',
    type: 'Concert',
    artist: 'Diljit Dosanjh',
    genre: 'punjabi/pop',
    date: '2026-07-10',
    time: '7:00 PM',
    location: 'Bengaluru',
    price: '₹3,000',
    description: 'Diljit brings his electrifying Dil-Luminati tour to Bengaluru — expect massive energy, punjabi anthems and non-stop dancing.',
    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'punjabi', 'bollywood', 'concert']
  },
  {
    id: '5',
    title: 'AP Dhillon: Forever Young World Tour',
    type: 'Concert',
    artist: 'AP Dhillon',
    genre: 'punjabi/r&b',
    date: '2026-09-20',
    time: '8:00 PM',
    location: 'Delhi',
    price: '₹3,500',
    description: 'AP Dhillon returns to India on his Forever Young World Tour with chart-topping hits and surprise collaborations.',
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'punjabi', 'r&b', 'concert', 'international']
  },
  {
    id: '6',
    title: 'Prateek Kuhad: The Way That Lovers Do',
    type: 'Concert',
    artist: 'Prateek Kuhad',
    genre: 'indie/folk',
    date: '2026-06-28',
    time: '7:00 PM',
    location: 'Bengaluru',
    price: '₹1,200',
    description: 'Prateek Kuhad performs his beloved indie folk catalogue in an intimate acoustic setting.',
    image: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'indie', 'folk', 'acoustic', 'concert']
  },
  {
    id: '7',
    title: 'Neha Kakkar: Neha Rocks Live',
    type: 'Concert',
    artist: 'Neha Kakkar',
    genre: 'bollywood/pop',
    date: '2026-10-05',
    time: '7:30 PM',
    location: 'Hyderabad',
    price: '₹1,800',
    description: 'Bollywood pop sensation Neha Kakkar live with her greatest dance numbers and party anthems.',
    image: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'bollywood', 'pop', 'concert', 'dance']
  },
  {
    id: '8',
    title: 'Divine: Jungli Sher Tour',
    type: 'Concert',
    artist: 'Divine',
    genre: 'rap/hip-hop',
    date: '2026-08-14',
    time: '8:00 PM',
    location: 'Mumbai',
    price: '₹1,500',
    description: 'Experience the best of Indian hip-hop with Divine performing his Gully Boy hits and new tracks live in Mumbai.',
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'rap', 'hip-hop', 'concert']
  },

  // ── FESTIVALS ──────────────────────────────────────────────────
  {
    id: '9',
    title: 'Sunburn Festival 2026',
    type: 'Festival',
    artist: 'Martin Garrix, Hardwell, KSHMR',
    genre: 'electronic/edm',
    date: '2026-12-28',
    time: '4:00 PM',
    location: 'Goa',
    price: '₹3,999',
    description: "Asia's biggest electronic dance music festival featuring international DJs across 4 stages over 3 days.",
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'festival', 'edm', 'electronic', 'international']
  },
  {
    id: '10',
    title: 'NH7 Weekender Pune',
    type: 'Festival',
    artist: 'Various Artists',
    genre: 'indie/alternative',
    date: '2026-11-14',
    time: '2:00 PM',
    location: 'Pune',
    price: '₹2,500',
    description: "India's happiest music festival returns to Pune with a diverse lineup across multiple stages celebrating indie and alternative music.",
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'festival', 'indie', 'alternative', 'multi-day']
  },
  {
    id: '11',
    title: 'Magnetic Fields Festival',
    type: 'Festival',
    artist: 'Various Artists',
    genre: 'electronic/indie',
    date: '2026-12-05',
    time: '6:00 PM',
    location: 'Jaipur',
    price: '₹4,500',
    description: 'A three-day boutique music festival set in a stunning Rajasthani palace featuring electronic and indie artists from around the world.',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'festival', 'electronic', 'indie', 'boutique']
  },
  {
    id: '12',
    title: 'Lollapalooza India 2026',
    type: 'Festival',
    artist: 'The Strokes, Arlo Parks, Prateek Kuhad',
    genre: 'alternative/indie/pop',
    date: '2026-01-31',
    time: '12:00 PM',
    location: 'Mumbai',
    price: '₹5,999',
    description: 'The iconic global music festival arrives in Mumbai for two days of international and Indian acts across multiple stages.',
    image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'festival', 'international', 'alternative', 'indie', 'pop']
  },

  // ── SPORTS ─────────────────────────────────────────────────────
  {
    id: '13',
    title: 'IPL Final 2026',
    type: 'Sport',
    artist: null,
    genre: 'cricket',
    date: '2026-05-30',
    time: '7:00 PM',
    location: 'Ahmedabad',
    price: '₹1,500',
    description: 'The grand finale of IPL 2026 at the Narendra Modi Stadium — the biggest night in T20 cricket.',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    tags: ['sport', 'cricket', 'ipl', 'live']
  },
  {
    id: '14',
    title: 'India vs Australia — 1st Test Day 1',
    type: 'Sport',
    artist: null,
    genre: 'cricket',
    date: '2026-09-12',
    time: '9:30 AM',
    location: 'Chennai',
    price: '₹800',
    description: 'Day 1 of the first Test match between India and Australia at the iconic MA Chidambaram Stadium.',
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    tags: ['sport', 'cricket', 'international', 'test-cricket']
  },
  {
    id: '15',
    title: 'Pro Kabaddi League Finals 2026',
    type: 'Sport',
    artist: null,
    genre: 'kabaddi',
    date: '2026-10-18',
    time: '8:00 PM',
    location: 'Mumbai',
    price: '₹500',
    description: 'The thrilling finale of Pro Kabaddi League Season 11 — two of the best teams battle for the trophy.',
    image: 'https://images.unsplash.com/photo-1564585222527-c2777a5bc6cb?auto=format&fit=crop&w=800&q=80',
    tags: ['sport', 'kabaddi', 'pkl', 'live']
  },
  {
    id: '16',
    title: 'Indian Super League: Mumbai City vs Bengaluru FC',
    type: 'Sport',
    artist: null,
    genre: 'football',
    date: '2026-07-04',
    time: '7:30 PM',
    location: 'Mumbai',
    price: '₹400',
    description: 'High-stakes ISL clash between two fierce rivals at the DY Patil Stadium.',
    image: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=800&q=80',
    tags: ['sport', 'football', 'isl', 'live']
  },

  // ── STANDUP COMEDY ─────────────────────────────────────────────
  {
    id: '17',
    title: 'Zakir Khan: Haq Se Single',
    type: 'Standup',
    artist: 'Zakir Khan',
    genre: 'standup comedy',
    date: '2026-08-22',
    time: '7:00 PM',
    location: 'Delhi',
    price: '₹799',
    description: "Zakir Khan performs his beloved Haq Se Single special live — an evening of laughter and relatable desi stories.",
    image: 'https://images.unsplash.com/photo-1603190287605-e6ade32fa852?auto=format&fit=crop&w=800&q=80',
    tags: ['comedy', 'standup', 'hindi', 'live']
  },
  {
    id: '18',
    title: 'Rahul Subramanian: Kal Main Utha Nahi',
    type: 'Standup',
    artist: 'Rahul Subramanian',
    genre: 'standup comedy',
    date: '2026-09-07',
    time: '7:30 PM',
    location: 'Bengaluru',
    price: '₹699',
    description: "Rahul Subramanian's brand new stand-up special touring across India — absurdist and sharp observational comedy.",
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=800&q=80',
    tags: ['comedy', 'standup', 'english', 'live']
  },
  {
    id: '19',
    title: 'Biswa Kalyan Rath: Biswa Mast Aadmi',
    type: 'Standup',
    artist: 'Biswa Kalyan Rath',
    genre: 'standup comedy',
    date: '2026-08-30',
    time: '8:00 PM',
    location: 'Kolkata',
    price: '₹649',
    description: 'Biswa Kalyan Rath brings his signature intellectual yet hilarious comedy to his home city Kolkata.',
    image: 'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?auto=format&fit=crop&w=800&q=80',
    tags: ['comedy', 'standup', 'english', 'live']
  },
  {
    id: '20',
    title: 'Kenny Sebastian: Don\'t Be That Guy',
    type: 'Standup',
    artist: 'Kenny Sebastian',
    genre: 'standup comedy',
    date: '2026-07-18',
    time: '7:00 PM',
    location: 'Bengaluru',
    price: '₹749',
    description: 'Kenny Sebastian performs his acclaimed Don\'t Be That Guy special live — music, comedy and storytelling combined.',
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?auto=format&fit=crop&w=800&q=80',
    tags: ['comedy', 'standup', 'english', 'musical comedy', 'live']
  },
  {
    id: '21',
    title: 'Kapil Sharma Live',
    type: 'Standup',
    artist: 'Kapil Sharma',
    genre: 'standup comedy',
    date: '2026-10-12',
    time: '7:00 PM',
    location: 'Mumbai',
    price: '₹1,200',
    description: 'India\'s favourite comedian Kapil Sharma performs a live standup show for the first time in years.',
    image: 'https://images.unsplash.com/photo-1478147427282-58a87a120781?auto=format&fit=crop&w=800&q=80',
    tags: ['comedy', 'standup', 'hindi', 'live']
  },

  // ── SCREENINGS ─────────────────────────────────────────────────
  {
    id: '22',
    title: 'Sholay 50th Anniversary Screening',
    type: 'Screening',
    artist: 'Amitabh Bachchan (guest appearance)',
    genre: 'classic bollywood',
    date: '2026-08-15',
    time: '6:30 PM',
    location: 'Mumbai',
    price: '₹600',
    description: 'Celebrate 50 years of Sholay with a restored 4K screening followed by a panel discussion with the original cast.',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    tags: ['film', 'screening', 'bollywood', 'classic', 'anniversary']
  },
  {
    id: '23',
    title: 'MAMI Mumbai Film Festival 2026',
    type: 'Screening',
    artist: 'Various Filmmakers',
    genre: 'world cinema',
    date: '2026-10-22',
    time: '10:00 AM',
    location: 'Mumbai',
    price: '₹350',
    description: 'The 28th edition of the Mumbai Academy of Moving Image Film Festival showcasing world premieres and international cinema.',
    image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    tags: ['film', 'screening', 'international', 'festival', 'world cinema']
  },
  {
    id: '24',
    title: 'Open Air Cinema: Dilwale Dulhania Le Jayenge',
    type: 'Screening',
    artist: 'Shah Rukh Khan, Kajol',
    genre: 'bollywood romance',
    date: '2026-09-26',
    time: '7:30 PM',
    location: 'Delhi',
    price: '₹450',
    description: 'Watch the all-time classic DDLJ under the stars at a special open-air cinema event in Delhi.',
    image: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?auto=format&fit=crop&w=800&q=80',
    tags: ['film', 'screening', 'bollywood', 'open-air', 'romantic']
  },

  // ── TECH & EXPOS ───────────────────────────────────────────────
  {
    id: '25',
    title: 'Techfest 2026 — IIT Bombay',
    type: 'Expo',
    artist: 'Multiple Tech Speakers',
    genre: 'technology',
    date: '2026-09-05',
    time: '9:00 AM',
    location: 'Mumbai',
    price: '₹299',
    description: "Asia's largest science and technology festival hosted by IIT Bombay featuring workshops, talks and robotics competitions.",
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    tags: ['expo', 'tech', 'innovation', 'science']
  },
  {
    id: '26',
    title: 'India International Trade Fair 2026',
    type: 'Expo',
    artist: null,
    genre: 'trade & commerce',
    date: '2026-11-14',
    time: '10:00 AM',
    location: 'Delhi',
    price: '₹150',
    description: 'The 45th edition of India\'s premier trade fair at Pragati Maidan featuring 7,000+ exhibitors from 30+ countries.',
    image: 'https://images.unsplash.com/photo-1560523159-6b681a1e1852?auto=format&fit=crop&w=800&q=80',
    tags: ['expo', 'trade', 'business', 'international']
  },
  {
    id: '27',
    title: 'Bengaluru Tech Summit 2026',
    type: 'Expo',
    artist: 'Industry Leaders & Innovators',
    genre: 'technology',
    date: '2026-11-19',
    time: '9:00 AM',
    location: 'Bengaluru',
    price: '₹999',
    description: "One of Asia's top technology summits bringing together global technology leaders, startups, and innovators.",
    image: 'https://images.unsplash.com/photo-1593642532454-e138e28a63f4?auto=format&fit=crop&w=800&q=80',
    tags: ['expo', 'tech', 'innovation', 'startup', 'ai']
  },

  // ── CLASSICAL & CULTURAL ────────────────────────────────────────
  {
    id: '28',
    title: 'Jaipur Literature Festival 2026',
    type: 'Expo',
    artist: 'Authors & Literary Figures',
    genre: 'literature & culture',
    date: '2026-01-22',
    time: '9:00 AM',
    location: 'Jaipur',
    price: '₹0',
    description: "The world's largest free literary festival bringing together authors, thinkers and artists from across the globe.",
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    tags: ['literature', 'culture', 'free', 'festival', 'books']
  },
  {
    id: '29',
    title: 'Ravi Shankar Memorial Concert',
    type: 'Concert',
    artist: 'Anoushka Shankar',
    genre: 'indian classical',
    date: '2026-04-07',
    time: '6:30 PM',
    location: 'Kolkata',
    price: '₹800',
    description: 'Anoushka Shankar performs a tribute to her father Pandit Ravi Shankar at Netaji Indoor Stadium.',
    image: 'https://images.unsplash.com/photo-1504680177321-2e6a879aac86?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'classical', 'indian classical', 'sitar', 'concert']
  },
  {
    id: '30',
    title: 'Zakir Hussain: Tabla Maestro Live',
    type: 'Concert',
    artist: 'Zakir Hussain',
    genre: 'indian classical',
    date: '2026-05-09',
    time: '6:00 PM',
    location: 'Delhi',
    price: '₹1,000',
    description: 'Grammy-winning tabla legend Zakir Hussain performs at Siri Fort Auditorium in an evening of pure classical genius.',
    image: 'https://images.unsplash.com/photo-1550305080-4e029753abcf?auto=format&fit=crop&w=800&q=80',
    tags: ['music', 'classical', 'indian classical', 'tabla', 'concert']
  },
];

module.exports = { eventsList };
